## Importing the libraries

In [1]:
import numpy as np
import pandas as pd

## Importing and preprocessing the dataset

In [2]:
trainset = pd.read_csv('train.csv')

In [3]:
trainset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
testset = pd.read_csv('test.csv')

In [5]:
testset.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

## Drop unwanted data

In [6]:
trainset = trainset.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Fare','Cabin','Embarked'], axis=1)

In [7]:
trainset.head()

Survived  Pclass     Sex   Age
0         0       3    male  22.0
1         1       1  female  38.0
2         1       3  female  26.0
3         1       1  female  35.0
4         0       3    male  35.0

In [8]:
testset = testset.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Fare','Cabin','Embarked'], axis=1)

In [9]:
testset.head()

Pclass     Sex   Age
0       3    male  34.5
1       3  female  47.0
2       2    male  62.0
3       3    male  27.0
4       3  female  22.0

## 'Sex' data change from str to binary

In [10]:
trainset.Sex[trainset.Sex == 'male'] = 0
trainset.Sex[trainset.Sex == 'female'] = 1
testset.Sex[testset.Sex == 'male'] = 0
testset.Sex[testset.Sex == 'female'] = 1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid 

In [11]:
trainset.head()

Survived  Pclass Sex   Age
0         0       3   0  22.0
1         1       1   1  38.0
2         1       3   1  26.0
3         1       1   1  35.0
4         0       3   0  35.0

In [12]:
testset.head()

Pclass Sex   Age
0       3   0  34.5
1       3   1  47.0
2       2   0  62.0
3       3   0  27.0
4       3   1  22.0

In [13]:
trainset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
dtypes: float64(1), int64(2), object(1)
memory usage: 28.0+ KB


## Spliting trainset into dependent and independent variable

In [14]:
X = trainset.iloc[:, 1:].values
y = trainset.iloc[:, 0].values

In [15]:
print(X)

[[3 0 22.0]
 [1 1 38.0]
 [3 1 26.0]
 ...
 [3 1 nan]
 [1 0 26.0]
 [3 0 32.0]]


In [16]:
print(y)

[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1
 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 1 0 0 0 

## Filling up of missing values

In [17]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer (missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 2:])
X[:, 2:] = imputer.transform(X[:, 2:])

In [18]:
print(X)

[[3 0 22.0]
 [1 1 38.0]
 [3 1 26.0]
 ...
 [3 1 29.69911764705882]
 [1 0 26.0]
 [3 0 32.0]]


In [19]:
Xt = testset.iloc[:].values

In [20]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer (missing_values=np.nan, strategy='mean')
imputer.fit(Xt[:, 2:])
Xt[:, 2:] = imputer.transform(Xt[:, 2:])

In [21]:
print(Xt)

[[3 0 34.5]
 [3 1 47.0]
 [2 0 62.0]
 ...
 [3 0 38.5]
 [3 0 30.272590361445783]
 [3 0 30.272590361445783]]


## Splitting the dataset into the Training set and Test set

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [23]:
print(X_train)

[[3 0 29.69911764705882]
 [1 1 30.0]
 [2 1 34.0]
 ...
 [2 0 21.0]
 [3 1 29.69911764705882]
 [3 0 21.0]]


## Training 

In [26]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Confusion matrix

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[91 15]
 [19 54]]


0.8100558659217877

#Test data predictions

In [37]:
classifier = LogisticRegression(random_state = 0)
classifier.fit(X, y)

prediction = classifier.predict(Xt)

## Submission

In [40]:
testset_copy = pd.read_csv('test.csv')

In [42]:
submission = pd.DataFrame({
    'PassengerId':  testset_copy['PassengerId'],
    'Survived': prediction
})

submission.to_csv('submission.csv', index = False)

In [43]:
submission = pd.read_csv('submission.csv')
submission.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1